### ISSUE TITLE
通过higress 提供出来的 swagger-mcp,deerflow只识别到swagger3.0的mcp.swagger2.0的mcp直接报错,400 bad request.是否考虑兼容swagger2.0

### ISSUE THREAD

**Issue by jzwhack** [bytedance/deer-flow#349]
swagger2.0 json转成的yaml文件
``` 
server:
  name: openapi-server
tools:
  - name: aaaaaa
    description: aaaaaaaaa
    args:
      - name: request
        description: request
        type: object
        required: true
        properties:
          accessMode:
            type: string
          addressId:
            type: string
          appointDays:
            type: string
          appointSection:
            type: string
          appointmentNo:
            type: string
          appointmentTeam:
            type: string
          apptProdList:
            type: array
          endDate:
            type: string
          propertyList:
            type: array
          rspId:
            type: string
          rspSystemId:
            type: string
          startDate:
            type: string
          systemId:
            type: string
          useBackup:
            type: string
        position: body
    requestTemplate:
      url: /XXXXXXXXXXX/XXXXX/XXX/XXXX/XxX/
      method: POST
    responseTemplate: {}
```

swagger3.0 json的yaml文件
```
server:
  name: "openapi-server"
tools:
- args:
  - description: ""
    name: "accessMode"
    position: "body"
    type: "string"
  - description: ""
    name: "addressId"
    position: "body"
    type: "string"
  - description: ""
    name: "appointDays"
    position: "body"
    type: "string"
  - description: ""
    name: "appointSection"
    position: "body"
    type: "string"
  - description: ""
    name: "appointmentNo"
    position: "body"
    type: "string"
  - description: ""
    name: "appointmentTeam"
    position: "body"
    type: "string"
  - description: ""
    items:
      type: "object"
    name: "apptProdList"
    position: "body"
    type: "array"
  - description: ""
    items:
      type: "object"
    name: "propertyList"
    position: "body"
    type: "array"
  - description: ""
    name: "endDate"
    position: "body"
    type: "string"
  - description: ""
    name: "rspId"
    position: "body"
    type: "string"
  - description: ""
    name: "rspSystemId"
    position: "body"
    type: "string"
  - description: ""
    name: "startDate"
    position: "body"
    type: "string"
  - description: ""
    name: "systemId"
    position: "body"
    type: "string"
  - description: ""
    name: "useBackup"
    position: "body"
    type: "string"
  description: "aaaaaaaaaaaaaaa"
  name: "aaaaaaaaaaaaaaa"
  requestTemplate:
    method: "POST"
    url: "/xxx/xxx/x/x/x/x/x/x/v1"
  responseTemplate: {}
```
