### ISSUE TITLE
项目是否还继续使用 litellm？

### ISSUE THREAD

**Issue by incca** [bytedance/deer-flow#46]
使用 `OpenRouter` 作为 `Provider` 时，只需要在 `conf.yaml` 配置以下信息，也不需要在 `.env` 额外配置

```yaml
BASIC_MODEL:
  base_url: https://openrouter.ai/api/v1
  model: "google/gemini-2.5-pro-preview"
  api_key: your_openrouter_key
```

和 [configuration_guide.md](https://github.com/bytedance/deer-flow/blob/main/docs/configuration_guide.md?plain=1#L74-L90) 的描述有差异～

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/5ba24d8a-491e-4200-9a9b-9e65be74a3aa" />

是不是已经从 `litellm` 切换为 `langchain_openai`，不再依赖 `litellm` 了～
