### ISSUE TITLE
两个问题，一个是如何在conf.yaml中配置多个模型？一个是如何在web上设置中文？期待您的解答

### ISSUE THREAD

**Issue by fxnie** [bytedance/deer-flow#69]
![Image](https://github.com/user-attachments/assets/15f70e66-03ec-452b-85d3-157dc7ae22b3)

<img width="888" alt="Image" src="https://github.com/user-attachments/assets/c38c36e0-eb28-419c-999e-a977fc4a499f" />

**Comment by Sakura4036** [comment]
config models in `conf.yaml`
```yaml
BASIC_MODEL:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: "deepseek-v3-250324"
  # model: "doubao-1-5-pro-32k-250115"
  api_key: xxx
  max_tokens: 8192


REASONING_MODEL:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: "doubao-1-5-thinking-vision-pro-250428"
  api_key: xxx
  max_tokens: 8192

VISION_MODEL:
  base_url: https://ark.cn-beijing.volces.com/api/v3
  model: "doubao-1-5-thinking-vision-pro-250428"
  api_key: xxx
  max_tokens: 8192
```

change agent node model map in `src/config/agents.py`
```python
AGENT_LLM_MAP: dict[str, LLMType] = {
    "coordinator": "basic",
    "planner": "reasoning",
    "researcher": "reasoning",
    "coder": "basic",
    "reporter": "basic",
    "podcast_script_writer": "basic",
    "ppt_composer": "basic",
    "prose_writer": "basic",
}
```
